### ISSUE TITLE
Follow-Up on E-LatentLPIPS Release

### ISSUE THREAD

**Issue by Guaishou74851** [mingukkang/Diffusion2GAN#3]
Thank you for the incredible work on Diffusion2GAN and E-LatentLPIPS. The community is eagerly awaiting the release of E-LatentLPIPS, as it would greatly benefit ongoing research. Could you please share any updates on the release timeline? Appreciate your efforts and looking forward to it!

**Comment by mingukkang** [comment]
Thank you for your attention! I’ll be releasing the API for E-LatentLPIPS soon. It will include support for E-LatentLPIPS with SD15, SDXL, SD3, and Flux. :)

**Comment by Guaishou74851** [comment]
> Thank you for your attention! I’ll be releasing the API for E-LatentLPIPS soon. It will include support for E-LatentLPIPS with SD15, SDXL, SD3, and Flux. :)

Thanks for the update! Just a quick question: Will the E-LatentLPIPS API be compatible with SD2.1-base as well? I’m unsure if the VAEs in SD1.5 and SD2.1-base are the same.

**Comment by mingukkang** [comment]
I’ll check, and if the latent space of SD2.1 differs from the others, I’ll add it as well.

**Comment by mingukkang** [comment]
Please check 

https://github.com/mingukkang/elatentlpips

for e-latentlpips implementation!

**Comment by Guaishou74851** [comment]
> Please check
> 
> https://github.com/mingukkang/elatentlpips
> 
> for e-latentlpips implementation!

Thanks for your outstanding contribution! I'll try it out right away.
