### ISSUE TITLE
Request for Training Code Release - Multi-Scale Conditional Discriminator

### ISSUE THREAD

**Issue by Guaishou74851** [mingukkang/Diffusion2GAN#4]
Thank you for your excellent work on Diffusion2GAN! Would it be possible to release the training code? Specifically, I am looking for the details of implementing the multi-scale conditional discriminator, constructed and trained with the generator network. Having access to the code would greatly benefit those of us in the research community who are keen to explore and extend this approach. I appreciate your contributions and hope you can consider this request. Thank you for your time and consideration!

**Comment by mingukkang** [comment]
I’m sorry, but I won’t be able to release the model training code. If you have any questions, feel free to reach out to me on GitHub or via email.
